# Generated by Django 4.2.7 on 2023-12-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuraldata", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activations", models.JSONField()),
                ("activations_shape", models.JSONField()),
                ("gradients", models.JSONField()),
                ("gradients_shape", models.JSONField()),
                ("loss", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="Activation",
        ),
        migrations.DeleteModel(
            name="Gradient",
        ),
    ]
