# Generated by Django 4.2.7 on 2023-12-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuraldata", "0002_trainingdata_delete_activation_delete_gradient"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingdata",
            name="layer_order",
            field=models.JSONField(default=list),
        ),
    ]
