# Generated by Django 4.2.7 on 2023-12-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("neuraldata", "0003_trainingdata_layer_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingdata",
            name="test_loss",
            field=models.FloatField(default=0.0),
        ),
    ]
